package com;

public enum MessageType {
    NAME_REQUEST,
    USER_NAME,
    NAME_ACCEPTED,
    TEXT_EMAIL,
    TEXT_EMAIL_ERROR,
    TEXT_EMAIL_SUCCESS,
    FILE_EMAIL,
    FILE_EMAIL_ERROR,
    FILE_EMAIL_SUCCESS,
    LIST_OF_USERS_REQUEST,
    LIST_OF_USERS_RESPONSE,
}
